(******************************************************************************)
(*                                                                            *)
(*                         Anesthesia Dosing Rules                            *)
(*                                                                            *)
(*     Propofol and fentanyl induction/maintenance dosing by weight, age,     *)
(*     and ASA class. Models the therapeutic window between awareness and     *)
(*     respiratory depression.                                                *)
(*                                                                            *)
(*     "Gentlemen, this is no humbug."                                        *)
(*     – John Collins Warren, Massachusetts General Hospital, 1846            *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: January 5, 2026                                                  *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
